### ISSUE TITLE
back-end for the login page

### ISSUE THREAD

**Issue by MEKSankalpa** [MEKSankalpa/Player-IMS-For-Sport-Club#10]
**signup part ok**

**most important**

your database name should be **sportclub**
table name should be **user**

**here is colums of the table**
Id --auto increment
fname 
lname                                other all are varchar
uname
user_email,
user_contact,
con_password

**Comment by Hansajith98** [comment]
is anyone working for this?

**Comment by MEKSankalpa** [comment]
nope it's belongs to you

**Comment by Prabath03Dot** [comment]
I handle this.

**Comment by Hansajith98** [comment]
ok
