### ISSUE TITLE
back-end to for the view profile

### ISSUE THREAD

**Issue by MEKSankalpa** [MEKSankalpa/Player-IMS-For-Sport-Club#12]
**signup part ok**

**most important**

your database name should be **sportclub**

table name should be **user**

**here is colums of the table**

Id --auto increment
fname 
lname                                other all are varchar
uname
user_email,
user_contact,
con_password

**Comment by bbsharath52-MCA** [comment]
// table for register and login
create table 'user' (id  int(6) NOT NULL AUTO_INCREMENT, fname varchar(20), lname varchar(20), uname varchar(20), user_email varchar(20),  user_contact varchar(20),  con_password varchar(20));


// database
CREATE DATABASE 'sportclub';

**Comment by MEKSankalpa** [comment]
change to this no need not null to id
create table 'user' (id int(10)  AUTO_INCREMENT, fname varchar(100), lname varchar(100), uname varchar(100), user_email varchar(100), user_contact varchar(100), con_password varchar(100));

**Comment by bbsharath52-MCA** [comment]
create table 'user' (id int(6) AUTO_INCREMENT, fname varchar(20), lname varchar(20), uname varchar(20), user_email varchar(20), user_contact varchar(20), con_password varchar(20));

// database
CREATE DATABASE 'sportclub';

**Comment by bbsharath52-MCA** [comment]
what next to be included in this project?
