### ISSUE TITLE
back-end for the edit profile

### ISSUE THREAD

**Issue by MEKSankalpa** [MEKSankalpa/Player-IMS-For-Sport-Club#13]
**signup part ok**

most important

your database name should be sportclub

table name should be user

here is colums of the table

Id --auto increment
fname
lname other all are varchar
uname
user_email,
user_contact,
con_password

**Comment by ThiwankaShan** [comment]
i'll work on this

**Comment by MEKSankalpa** [comment]
create table 'user' (id int(10) AUTO_INCREMENT, fname varchar(100), lname varchar(100), uname varchar(100), user_email varchar(100), user_contact varchar(100), con_password varchar(100));

datbase 'sportclub'
